#!/usr/bin/env bash
#displays username, id, and home directory for each line of /etc/passwd
while read line
do
    user=$(echo "$line" | cut -d':' -f1)
    uid=$(echo "$line" | cut -d':' -f3)
    home=$(echo "$line" | cut -d':' -f6)
    echo "$user $uid $home"
done < /etc/passwd
