#!/usr/bin/env bash
#to get info about school file
if [ -f school ]
then
    echo "school is a regular file"
    if [ ! -s school ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -e echool ]
    then
        echo "school file exists"
    else
        echo "school file does not exist"
    fi
fi
