#!/usr/bin/env bash
#To do multiple things
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" 15
trap "echo 'Y U no love me?!'" 2
trap "sudo rm /var/run/myscript.pid; exit" 3
while true
do
    echo "To infinity and beyond"
    sleep 2
done
